spring:
  datasource:
    dbcp2:
      url: jdbc:h2:mem:testdb;MODE=MSSQLServer
      #      url: jdbc:h2:mem:;MODE=MSSQLServer
      username: ren
      password: password
      driver-class-name: org.h2.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  h2:
    console:
      enabled: true
      path: /h2-console
    profiles:
      active: local

  servlet:
    multipart:
      enabled: true
      location: c:\\upload
      max-request-size: 300MB
      max-file-size: 50MB


server:
  port: 8080

security.basic.enabled: false
management.security.enabled: false
file.dir: